name: Hourly DB Export

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  export-db-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      
      - name: Install dependencies
        run: |
          go mod tidy
          go get github.com/tursodatabase/libsql-client-go/libsql
      
      - name: Build and run
        env:
          TURSO_DATABASE_NAME : ${{ secrets.TURSO_DATABASE_NAME }}
          TURSO_DATABASE_AUTH_TOKEN: ${{ secrets.TURSO_DATABASE_AUTH_TOKEN }}
        run: |
          # Build and run the application
          go run sync_db.go
      
      - name: Commit and push if changes exist
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # Add any new files that might have been created
          git add posts/
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-export posts from database"
            git push
          fi
